tr translated
UB-Mannheim/PalMA pull request #215
Opened 2024-01-09 21:57 UTC by AYakici

2024-01-09 21:58 UTC, AYakici commented
translated en to tr , Student 9 AyhanYakici

2024-01-10 06:24 UTC, stweil commented on locale/tr_TR.UTF-8/LC_MESSAGES/palma.po
> +"Language: en\n"
Please update these lines, too.

2024-01-10 06:26 UTC, stweil commented on locale/tr_TR.UTF-8/LC_MESSAGES/palma.po
> +msgstr ""
Sayfa yukarı?

2024-01-10 06:34 UTC, stweil requested changes
Thanks a lot for adding a new language. Please see my other comments for the small parts which still need changes.

Please note that your contribution will be honored in the README [here](https://github.com/UB-Mannheim/PalMA/tree/master/locale) after your pull request was merged. Therefore your pull request should have your full real name as author and in the signature. That's currently not the case. Please try to fix that.

2024-01-15 20:47 UTC, closed without merging